### ISSUE TITLE
Add a short test of the package

### ISSUE THREAD

**Issue by olexandr-konovalov** [pjastr/NoCK#1]
The package has no test files. It is recommended to have a `TestFile` component in `PackageInfo.g` to specify a short test (to run for no more than several minutes) which may be used to check that a package works as expected. For deposited packages, these tests are run regularly as a part of the standard GAP test suite. Please see `?TestPackage`, `?Tests files for a GAP package` and also `?TestDirectory` for more information. You can find a sample setup in the example package at https://github.com/gap-packages/example.

**Comment by pjastr** [comment]
Thx for tip. Test was added in version 1.1.
