### ISSUE TITLE
Use ReleaseTools for releases

### ISSUE THREAD

**Issue by olexandr-konovalov** [pjastr/NoCK#4]
This is a follow-up from #3. Looking at the history of gh-pages branch at https://github.com/pjastr/NoCK/commits/gh-pages I see a lot of manual updates, that's not productive and error prone - I really recommend using https://github.com/gap-system/ReleaseTools by @fingolfin which automates publishing a release and makes it a mater of seconds.

**Comment by fingolfin** [comment]
@pjastr any chance for an update? If you are not able to or are not interested in maintaining this package anymore, you can also migrate it to http://github.com/gap-packages and hand over maintenance to the GAP team. That would only about making releases, and doing minor, technical only updates; you'd of course stay as authors, and can resume doing maintenance yourself at any time.

**Comment by pjastr** [comment]
@fingolfin Thank you for your message. Currently, due to many responsibilities, it is difficult for me to perform the migration, because I work on Windows. I know little about Linux. Please send me an instruction and send me a migration instruction to https://github.com/gap-packages

**Comment by fingolfin** [comment]
@pjastr I've sent you an invitation to join the `gap-packages` organization, you should have received an email. Once you accept that, you can transfer this repository there [via these instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository).

Once that's done, I can take care of the rest (merge PRs, make a release, update website).

**Comment by pjastr** [comment]
@fingolfin Thanks for the instruction. The transfer is complete.

**Comment by fingolfin** [comment]
Release 1.5 is out
