### ISSUE TITLE
typo on https://pjastr.github.io/NoCK/

### ISSUE THREAD

**Issue by dimpase** [pjastr/NoCK#5]
compu*ti*tation

**Comment by olexandr-konovalov** [comment]
Which is perhaps because the website is handcrafted, instead of using an automated procedure - see #4. If you will make a new release using https://github.com/gap-system/ReleaseTools, the website will be generated automatically from `PackageInfo.g`.

**Comment by fingolfin** [comment]
Resolved (homepage is now at https://gap-packages.github.io/NoCK/)
